# -*- coding: utf-8 -*-
"""VideoGuide.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BewisjMZcjuuXTtoqWeB-N9UaFJe2l-R
"""

import os
os.environ["GOOGLE_API_KEY"] = "IzaSyBcqInDNJ3WzXNV8EkwSCTV9xkk"

!pip install -q youtube-transcript-api langchain-community \
               langchain-google-genai faiss-cpu tiktoken python-dotenv google-generativeai

from youtube_transcript_api import YouTubeTranscriptApi, TranscriptsDisabled
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate

"""**Indexing**"""

from youtube_transcript_api._errors import TranscriptsDisabled

video_id = "Gfr50f6ZBvo"

try:
    fetched_transcript = YouTubeTranscriptApi().fetch(video_id, languages=['en'])
    transcript_list = fetched_transcript.to_raw_data()
    transcript = " ".join(chunk["text"] for chunk in transcript_list)
    print(transcript)

except TranscriptsDisabled:
    print("No captions available for this video.")
except Exception as e:
    print(f"An error occurred: {e}")

transcript_list

transcript



"""**Text Splitting**"""

splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
chunks = splitter.create_documents([transcript])

chunks

len(chunks)

chunks[100]

"""**Embedding Generation and Store it into Vector Store**"""

from langchain_community.embeddings import HuggingFaceEmbeddings

embedding = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

vector_store = FAISS.from_documents(chunks,embedding)

vector_store.index_to_docstore_id

vector_store.get_by_ids(['9b7f0c7f-cc5c-435e-b56c-0261da9a0e80'])

"""**Retrieval**"""

retriever = vector_store.as_retriever(search_type='similarity',search_kwargs={"k":4})

retriever.invoke('what is deepmind')

"""**Augmentation**"""

prompt = PromptTemplate(
    template="""
      You are a helpful assistant.
      Answer ONLY from the provided transcript context.
      If the context is insufficient, just say you don't know.

      {context}
      Question: {question}
    """,
    input_variables = ['context', 'question']
)

question          = "is the topic of nuclear fusion discussed in this video? if yes then what was discussed"
retrieved_docs    = retriever.invoke(question)

retrieved_docs

context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
context_text

final_prompt = prompt.invoke({'context':context_text, 'question':question})

"""**Generations**"""

model = ChatGoogleGenerativeAI(model='gemini-2.5-flash')

result = model.invoke(final_prompt)

print(result.content)

"""**Using Chains**"""

from langchain_core.runnables import RunnableParallel, RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser

def format_docs(retrieved_docs):
  context_text = "\n\n".join(doc.page_content for doc in retrieved_docs)
  return context_text

parallel_chain = RunnableParallel({
    'context': retriever | RunnableLambda(format_docs),
    'question': RunnablePassthrough()
})

parser = StrOutputParser()
final_chain = parallel_chain | prompt | model | parser

final_chain.invoke('summarize the video')

